### PR TITLE
Fix signature for RLP encoding

### LINKED ISSUE #97: Fix signature for RLP encoding

### PR DESCRIPTION
**Pull request by IAvecilla**
Trying to deploy in the new [`era-test-node`](https://github.com/matter-labs/era-test-node), we discovered an issue related to the signature and the RLP encoding for the transaction. This PR fixes that error, enabling deployment in both `local-setup` (docker nodes) and the new memory node.

closes #97

### CODE REVIEW

File: src/eip712/transaction.rs [hunk 1]
```diff
@@ -29,6 +29,8 @@ pub struct Eip712Transaction {
     pub data: Bytes,
     pub factory_deps: Vec<Bytes>,
     pub paymaster_input: Bytes,
+    #[serde(skip_serializing)]
```
Comment (jpcenteno) [inline src/eip712/transaction.rs:32]: Just curious about why / what is this line doing?

File: src/eip712/transaction_request.rs [hunk 2]
```diff
@@ -181,30 +184,31 @@ impl Eip712TransactionRequest {
...
+            self.custom_data.rlp_append(&mut stream);
+        } else if let Some(signature) = signature {
+            let tx = self.clone().custom_data(
+                self.clone()
+                    .custom_data
+                    .custom_signature(signature.to_vec()),
+            );
+            tx.custom_data.rlp_append(&mut stream);
+        } else {
+            return Err(Eip712Error::Message("No signature provided".to_owned()));
```
Comment (jpcenteno) [inline src/eip712/transaction_request.rs:208]: Is it a good idea to fail when the `signature` parameter equals `None` when to its type is `Option<Signature>`?

**Review by jpcenteno — CHANGES_REQUESTED** [review]
I didn't see any new test. Did we had failing tests before these changes? In my opinion, bug fix PRs should include tests to ensure the bug does not happen again.

File: src/eip712/transaction.rs (hunk 1 above)
Comment (IAvecilla) [reply src/eip712/transaction.rs]: It was an old patch for some endpoint related with the memory node but it seems that is already fixed so it's not necessary anymore. Good catch

File: src/eip712/transaction_request.rs (hunk 2 above)
Comment (IAvecilla) [reply src/eip712/transaction_request.rs:208]: It fails only when both `custom_signature` and `signature` are `None`, as at least one of them must be present.

**Comment by IAvecilla** [comment]
In terms of testing for this particular pull request, this fix specifically addresses the deploy feature in the memory node. To test it, you can change the ERA_CHAIN_ID to match the one in the memory node and set the environment variable to correspond to the memory node's URL.

Looking ahead, the plan could involve either migrating this testing procedure to the memory node directly or creating two distinct test suites—one for working with the node in a Docker environment and the other for the memory node.

File: src/eip712/transaction_request.rs (hunk 2 above)
Comment (jpcenteno) [reply src/eip712/transaction_request.rs:208]: Ok. We should discuss in the future if it makes sense to leverage the type system to prevent an invalid state.

Comment (jpcenteno) [reply src/eip712/transaction_request.rs:208]: I created a ticket just to track the discussion https://github.com/lambdaclass/zksync-web3-rs/issues/101.

Comment (jpcenteno) [reply src/eip712/transaction_request.rs:208]: I'm marking this chat as resolved.

**Review by jpcenteno — APPROVED** [review]

**Review by mationorato — APPROVED** [review]
LGTM
